// Specs por modelo y version. Generado desde fichas_tecnicas_extracto.md
const SPECS = {
  virtus: {
    msi: {
      motor: {
        nombre: '1.6 MSI',
        subtitulo: '1.598 cc · 4 cilindros · nafta · Euro 6 Plus',
        potencia: '110 CV',
        torque: '155 Nm',
        torqueRpm: '@ 4.000 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Aire acondicionado',
        'VW Play 10" con Wireless App-Connect',
        'Control crucero',
        '6 airbags (frontales + laterales + cortina)',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + EBD',
        'ESC + HHC',
        'ISOFIX',
        'DRL LED',
        'Faros Eco LED y traseros LED',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Volante multifunción',
        'Levantacristales eléctricos',
        'Asientos en tela',
      ],
      exterior: [
        'Llantas de aleación 15"',
        'DRL LED',
        'Faros Eco LED',
        'Luces traseras LED',
      ],
      tecnologia: [
        'VW Play 10" con Wireless App-Connect',
        'Volante multifunción',
      ],
    },
    trendline: {
      motor: {
        nombre: '1.6 MSI',
        subtitulo: '1.598 cc · 4 cilindros · nafta · Euro 6 Plus',
        potencia: '110 CV',
        torque: '155 Nm',
        torqueRpm: '@ 4.000 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Cargador inalámbrico',
        'Sensor estacionamiento trasero',
        'Volante y palanca en cuero',
        'Faros antiniebla delanteros',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + EBD',
        'ESC + HHC',
        'ISOFIX',
        'Faros antiniebla delanteros',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Apoyabrazos central delantero',
        'Cargador inalámbrico',
        'Sensor de estacionamiento trasero',
        'Palanca de cambios en cuero',
        'Volante en cuero',
        'Apoyacabezas ajustables',
        'Iluminación cortesía en guantera y baúl',
      ],
      exterior: [
        'Llantas de aleación 15"',
        'DRL LED',
        'Faros Eco LED',
        'Luces traseras LED',
      ],
      tecnologia: [
        'VW Play 10" con Wireless App-Connect',
        'Volante multifunción en cuero',
      ],
    },
    highline: {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 1.750 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Climatizador automático',
        'Cámara + sensores estacionamiento delanteros y traseros',
        'KESSY (acceso sin llave)',
        'Active Info Display',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + EBD · ESC + HHC',
        'ISOFIX',
        'Indicador presión de neumáticos',
        'Detector de fatiga',
        'Asistente de mantenimiento de carril',
        'Faros antiniebla delanteros',
      ],
      confort: [
        'Climatizador automático',
        'Difusores de aire traseros',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Sensor estacionamiento delantero y trasero',
        'Cámara estacionamiento trasera',
        'Coming & Leaving Home',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Tapizado en cuero sintético',
      ],
      exterior: [
        'Llantas de aleación 17"',
        'DRL LED',
        'Faros Eco LED',
        'Espejos con plegado eléctrico y Tilt Down',
      ],
      tecnologia: [
        'VW Play 10" Conectada con Wireless App-Connect',
        'Active Info Display',
        'Mi VW Connect',
        '4 puertos USB',
      ],
    },
    exclusive: {
      motor: {
        nombre: '1.4 250 TSI',
        subtitulo: '1.395 cc · 4 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '150 CV',
        torque: '250 Nm',
        torqueRpm: '@ 1.500 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Control crucero adaptativo (ACC)',
        'Freno autónomo de emergencia',
        'Llantas de aleación 18"',
        'Selector de perfil de conducción',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + EBD · ESC + HHC',
        'Freno autónomo de emergencia',
        'Control crucero adaptativo (ACC)',
        'Indicador presión de neumáticos',
        'Detector de fatiga',
        'Asistente de mantenimiento de carril',
      ],
      confort: [
        'Climatizador automático',
        'Difusores de aire traseros',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Cámara y sensores estacionamiento',
        'Coming & Leaving Home',
        'Sistema Start & Stop',
        'Selector de perfil de conducción',
        'Tapizado en cuero sintético Exclusive',
      ],
      exterior: [
        'Llantas de aleación 18"',
        'Frenos a disco ventilados en las 4 ruedas',
        'Carcasa de espejos color gris',
        'DRL LED',
        'Faros Eco LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con Wireless App-Connect',
        'Active Info Display',
        'Mi VW Connect',
        '4 puertos USB',
      ],
    },
  },

  tera: {
    trendline: {
      motor: {
        nombre: '1.6 MSI',
        subtitulo: '1.598 cc · 4 cilindros · nafta · Euro 6 Plus',
        potencia: '110 CV',
        torque: '155 Nm',
        torqueRpm: '@ 4.000 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Aire acondicionado',
        'VW Play 10" con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        '6 airbags (frontales + laterales + cortina)',
        'Detector de fatiga',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        'Detector de fatiga',
        'Control crucero',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Volante multifunción',
        'Sensor estacionamiento trasero',
        '6 parlantes',
      ],
      exterior: [
        'Llantas de acero 16"',
        'Faros VW LED',
        'Luces traseras Click-Clack LED',
        'Espejos color carrocería',
      ],
      tecnologia: [
        'VW Play 10" con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        '6 parlantes',
      ],
    },
    comfort: {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 1.750-4.250 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Llantas de aleación 16" diamantadas',
        'VW Play 10" Conectada',
        'Mi VW Connect',
        'Volante en cuero con levas',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        'Detector de fatiga',
        'Control crucero',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Apoyabrazos delantero',
        'Volante en cuero con levas',
        'Sensor estacionamiento trasero',
        '6 parlantes',
      ],
      exterior: [
        'Llantas de aleación 16" diamantadas',
        'Faros VW LED',
        'Luces traseras Click-Clack LED',
        'Espejos color carrocería',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Mi VW Connect',
        '6 parlantes',
      ],
    },
    high: {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 1.750-4.250 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Control crucero adaptativo (ACC)',
        'Climatizador automático',
        'Cámara visión trasera',
        'Active Info Display 10,25"',
        'Detector punto ciego con tráfico cruzado',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'Frenado de emergencia post colisión',
        'Control crucero adaptativo (ACC)',
        'Asistente mantenimiento de carril',
        'Detector punto ciego con tráfico cruzado trasero',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Climatizador automático 1 zona',
        'Apoyabrazos delantero',
        'Volante en cuero con levas',
        'Respaldo trasero plegable 1/3-2/3',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Cargador inalámbrico',
        'Coming & Leaving Home',
        'Tapizado cuero ecológico',
      ],
      exterior: [
        'Llantas de aleación 17" diamantadas',
        'Faros VW LED',
        'Luces traseras Click-Clack LED',
        'Espejos color carrocería',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        'USB Tipo C traseras',
        'Ambient Light',
      ],
    },
    outfit: {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 1.750-4.250 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Techo bitono color negro',
        'Llantas 17" oscurecidas',
        'Espejos color negro exclusivo',
        'Tapizado cuero ecológico Outfit',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'Frenado de emergencia post colisión',
        'Control crucero adaptativo (ACC)',
        'Asistente mantenimiento de carril',
        'Detector punto ciego con tráfico cruzado trasero',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Climatizador automático 1 zona',
        'Apoyabrazos delantero',
        'Volante en cuero con levas',
        'Respaldo trasero plegable 1/3-2/3',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Cargador inalámbrico',
        'Coming & Leaving Home',
        'Tapizado cuero ecológico Outfit',
      ],
      exterior: [
        'Llantas de aleación 17" oscurecidas',
        'Techo bitono color negro',
        'Espejos color negro exclusivo Outfit',
        'Faros VW LED',
        'Luces traseras Click-Clack LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        'USB Tipo C traseras',
        'Ambient Light',
      ],
    },
  },

  saveiro: {
    comfortline: {
      motor: {
        nombre: '1.6 MSI',
        subtitulo: '1.598 cc · 4 cilindros · nafta',
        potencia: '110 CV',
        torque: '155 Nm',
        torqueRpm: '@ 4.000 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción trasera',
      },
      destacados: [
        'Aire acondicionado',
        'Composition Touch 9" con App-Connect',
        'Volante multifunción',
        'ESP con estabilización para remolques',
      ],
      seguridad: [
        '2 airbags (conductor + pasajero)',
        'ABS',
        'ESP con estabilización para remolques',
        'ASR + EDL (bloqueo electrónico de diferencial)',
        'HHC',
        'Alarma antirrobo con monitoreo de habitáculo',
        'Inmovilizador electrónico',
      ],
      confort: [
        'Aire acondicionado',
        'Levantacristales eléctricos delanteros',
        'Asiento conductor con ajuste de altura',
        'Retrovisores eléctricos',
        'Cierre centralizado con control remoto',
        'Volante multifunción',
        'Computadora de a bordo',
      ],
      exterior: [
        'Llantas de acero 15"',
        'Carcasa de espejos color carrocería',
        'Manijas color carrocería',
        'Tercera luz de stop',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Android Auto / Apple CarPlay',
        '6 parlantes',
        'Toma 12V',
      ],
    },
  },

  nivus: {
    'trendline-mt': {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 1.500-3.750 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Aire acondicionado',
        'VW Play 10" con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Cámara + sensor estacionamiento trasero',
        'Coming & Leaving Home',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        '3 apoyacabezas traseros',
        'Control crucero',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Coming & Leaving Home',
        'Espejos con Tilt Down',
        'Sensor estacionamiento trasero',
        'Cámara estacionamiento trasera',
      ],
      exterior: [
        'Llantas de aleación 16"',
        'Neumaticos 205/60',
        'Faros VW LED',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        '4+2 parlantes',
      ],
    },
    'trendline-at': {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-4.000 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Frenos a disco en las 4 ruedas',
        'Apoyabrazos delantero con salida de aire traseras',
        'USB Tipo C traseras',
        'Palanca de cambios en cuero',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        '3 apoyacabezas traseros',
        'Control crucero',
        'Frenos a disco en las 4 ruedas',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Coming & Leaving Home',
        'Espejos con Tilt Down',
        'Sensor estacionamiento trasero',
        'Cámara estacionamiento trasera',
        'Apoyabrazos delantero central con salida de aire traseras',
        'Palanca de cambios revestida en cuero',
      ],
      exterior: [
        'Llantas de aleación 16"',
        'Neumaticos 205/60',
        'Faros VW LED',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        '4+2 parlantes',
        'USB Tipo C traseras (2)',
      ],
    },
    comfortline: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-4.000 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'VW Play 10" Conectada',
        'Llantas de aleación 17"',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        '3 apoyacabezas traseros',
        'Control crucero',
        'Espejo interior anti-encandilamiento automático',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Coming & Leaving Home',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Cámara estacionamiento trasera',
        'Apoyabrazos delantero con salida de aire traseras',
      ],
      exterior: [
        'Llantas de aleación 17"',
        'Neumaticos 205/55',
        'Faros VW LED',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Mi VW Connect',
        '4+2 parlantes',
        'USB Tipo C traseras',
      ],
    },
    highline: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-4.000 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Travel Assist + ACC adaptativo',
        'Climatizador táctil automático',
        'Active Info Display 10,25"',
        'Grilla LED frontal iluminada',
        'Detector punto ciego con tráfico cruzado',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'AEB (frenado autónomo de emergencia)',
        'ACC adaptativo + Travel Assist',
        'Asistente mantenimiento de carril con asistente en tráfico',
        'Detector punto ciego con tráfico cruzado trasero',
        'Detector de fatiga',
      ],
      confort: [
        'Climatizador táctil automático 1 zona',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Coming & Leaving Home',
        'Sensor estacionamiento delantero y trasero',
        'Cámara estacionamiento trasera',
        'Espejos rebatibles eléctricos',
        'Levas al volante',
        'Tapizado cuero ecológico',
      ],
      exterior: [
        'Llantas de aleación 17"',
        'Grilla LED frontal iluminada',
        'Faros VW LED',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        '4+2 parlantes',
        'USB Tipo C traseras',
      ],
    },
    outfit: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 6',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-4.000 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Techo bitono color negro',
        'Llantas 17" pintadas color negro',
        'Espejos exteriores color negro',
        'Insignias traseras y laterales en negro',
        'Tapizado cuero ecológico Outfit',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'AEB (frenado autónomo de emergencia)',
        'ACC adaptativo + Travel Assist',
        'Asistente mantenimiento de carril con asistente en tráfico',
        'Detector punto ciego con tráfico cruzado trasero',
        'Detector de fatiga',
      ],
      confort: [
        'Climatizador táctil automático 1 zona',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Coming & Leaving Home',
        'Sensor estacionamiento delantero y trasero',
        'Cámara estacionamiento trasera',
        'Espejos rebatibles eléctricos',
        'Tapizado cuero ecológico Outfit',
      ],
      exterior: [
        'Llantas de aleación 17" pintadas color negro',
        'Techo bitono color negro',
        'Espejos exteriores color negro',
        'Barras de techo silver',
        'Insignias traseras y laterales en negro',
        'Grilla LED frontal iluminada',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        '4+2 parlantes',
        'USB Tipo C traseras',
      ],
    },
  },

  't-cross': {
    'trendline-mt': {
      motor: {
        nombre: '1.0 170 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 5',
        potencia: '101 CV',
        torque: '170 Nm',
        torqueRpm: '@ 2.000-4.000 rpm',
        caja: 'Manual 5 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Aire acondicionado',
        'VW Play 10" Conectada con App-Connect',
        'AEB con detección de peatones',
        'VW Digital Cockpit 8"',
        'Control crucero',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        '3 apoyacabezas traseros',
        'AEB con detección de peatones',
        'Frenado emergencia post colisión',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Volante multifunción en cuero',
        'Sensor estacionamiento trasero',
        '2+2 parlantes',
      ],
      exterior: [
        'Llantas de aleación 16"',
        'Neumaticos 205/60',
        'Faros LED con DRL',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Mi VW Connect',
        '2+2 parlantes',
      ],
    },
    'trendline-at': {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 5',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-3.500 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Frenos a disco en las 4 ruedas',
        'Apoyabrazos delantero corredizo',
        'Volante en cuero con levas',
        'USB Tipo C traseras',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        '3 apoyacabezas traseros',
        'AEB con detección de peatones',
        'Frenado emergencia post colisión',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Aire acondicionado',
        'Control crucero',
        'Apoyabrazos delantero central corredizo con guardado',
        'Volante en cuero con levas',
        'Sensor estacionamiento trasero',
        '4+2 parlantes',
      ],
      exterior: [
        'Llantas de aleación 16"',
        'Neumaticos 205/60',
        'Faros LED con DRL',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Mi VW Connect',
        '4+2 parlantes',
        'USB Tipo C traseras',
      ],
    },
    comfortline: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 5',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-3.500 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Control crucero adaptativo (ACC)',
        'Climatizador automático',
        'KESSY (acceso sin llave)',
        'Cámara visión trasera',
        'Cargador inalámbrico',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'ISOFIX',
        'AEB con detección de peatones',
        'Control crucero adaptativo (ACC)',
        'Frenado emergencia post colisión',
        'Indicador presión de neumáticos',
      ],
      confort: [
        'Climatizador automático 1 zona',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Asiento conductor con regulación lumbar',
        'Cámara visión trasera',
        'Espejos con Tilt Down',
        'Apoyabrazos delantero central corredizo',
        'Tapizado cuero ecológico',
        'Iluminación cortesía en guantera',
      ],
      exterior: [
        'Llantas de aleación 17"',
        'Neumaticos 205/55',
        'Faros LED con DRL',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'VW Digital Cockpit 8"',
        'Mi VW Connect',
        '4+2 parlantes',
        'USB Tipo C traseras',
      ],
    },
    highline: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 5',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-3.500 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Travel Assist + Park Assist',
        'Techo solar panorámico',
        'Active Info Display 10,25"',
        'Grilla LED frontal iluminada',
        'Detector punto ciego con tráfico cruzado',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'AEB con detección de peatones',
        'Travel Assist + ACC adaptativo',
        'Asistente mantenimiento de carril con asistente en tráfico',
        'Detector punto ciego con tráfico cruzado trasero',
        'Detector de fatiga',
      ],
      confort: [
        'Climatizador automático 1 zona',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Sensor estacionamiento delantero y trasero',
        'Park Assist (estacionamiento automático)',
        'Techo solar panorámico',
        'Espejos rebatibles eléctricos',
      ],
      exterior: [
        'Llantas de aleación 17"',
        'Grilla LED frontal iluminada',
        'Barras de techo plateadas',
        'Faros LED con DRL',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        '4+2 parlantes',
        'Ambient Light',
      ],
    },
    extreme: {
      motor: {
        nombre: '1.0 200 TSI',
        subtitulo: '999 cc · 3 cilindros turbo · nafta · Euro 5',
        potencia: '116 CV',
        torque: '200 Nm',
        torqueRpm: '@ 2.000-3.500 rpm',
        caja: 'Tiptronic 6 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Techo bitono color negro',
        'Llantas 17" con tecnología Seal Inside',
        'Espejos exteriores color negro',
        'Barras de techo en color negro',
        'Techo solar panorámico',
      ],
      seguridad: [
        'Airbags frontales + laterales + cortina',
        'ABS + ESC + HHC',
        'AEB con detección de peatones',
        'Travel Assist + ACC adaptativo',
        'Asistente mantenimiento de carril con asistente en tráfico',
        'Detector punto ciego con tráfico cruzado trasero',
        'Detector de fatiga',
      ],
      confort: [
        'Climatizador automático 1 zona',
        'KESSY (acceso sin llave)',
        'Cargador inalámbrico',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Sensor estacionamiento delantero y trasero',
        'Park Assist (estacionamiento automático)',
        'Techo solar panorámico',
        'Espejos rebatibles eléctricos',
      ],
      exterior: [
        'Llantas de aleación 17" con tecnología Seal Inside',
        'Techo bitono color negro',
        'Espejos exteriores color negro',
        'Barras de techo en color negro',
        'Grilla LED frontal iluminada',
        'Light Strip trasero LED',
      ],
      tecnologia: [
        'VW Play 10" Conectada con App-Connect sin cable',
        'Active Info Display 10,25"',
        'Mi VW Connect',
        '4+2 parlantes',
        'Ambient Light',
      ],
    },
  },

  vento: {
    gli: {
      motor: {
        nombre: '2.0 350 TSI',
        subtitulo: '1.984 cc · 4 cilindros turbo · nafta · Euro 6',
        potencia: '230 CV',
        torque: '350 Nm',
        torqueRpm: '@ 1.500-4.600 rpm',
        caja: 'DSG 7 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Asientos con calefacción, ventilación y masajes',
        'Travel Assist con stop & go',
        'Techo panorámico',
        'Llantas 18" Belvedere',
        'Climatizador 2 zonas táctil',
      ],
      seguridad: [
        'Airbags conductor + acompañante (con desactivación)',
        '2 airbags cortina + 2 laterales',
        'Travel Assist con stop & go',
        'ACC adaptativo con limitador',
        'AEB con detección de peatones',
        'Detector punto ciego con tráfico cruzado trasero',
        'Lane Assist + Emergency Assist',
      ],
      confort: [
        'Climatizador automático 2 zonas táctil',
        'Asiento conductor eléctrico con memoria',
        'Asientos con calefacción y ventilación',
        'KESSY (acceso sin llave)',
        'Freno de estacionamiento eléctrico con Auto Hold',
        'Pedales deportivos en aluminio',
        'Tapizado en cuero',
        'Volante deportivo en cuero con levas',
        'Sensor estacionamiento delantero y trasero',
      ],
      exterior: [
        'Llantas de aleación 18" Belvedere (235/55 R18)',
        'Faros VW LED con asistencia luz de carretera',
        'Grilla frontal LED',
        'Luces traseras LED con Light Strip',
        'Doble salida de escape trasero',
        'Techo panorámico',
      ],
      tecnologia: [
        'VW Play Connect 10" semiflotante',
        'Active Info Display 100% digital',
        'App-Connect sin cable',
        'Cargador inductivo',
        'Cámara visión trasera',
        'Selector perfil de conducción',
      ],
    },
  },

  amarok: {
    trendline: {
      motor: {
        nombre: '2.0 TDI',
        subtitulo: '1.968 cc · 4 cilindros turbodiesel · common-rail',
        potencia: '140 CV',
        torque: '340 Nm',
        torqueRpm: '@ 1.600 rpm',
        caja: 'Manual 6 velocidades',
        traccion: '4x2 (tracción trasera)',
      },
      destacados: [
        'Composition Touch 9" con App-Connect',
        'Bloqueo mecánico de diferencial',
        'Climatizador semi-automático',
        '6 airbags',
        'Llantas Korama 16"',
      ],
      seguridad: [
        '2 airbags frontales + 2 laterales + 2 cortina',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Bloqueo mecánico de diferencial + EDS',
        'ISOFIX',
      ],
      confort: [
        'Climatizador semi-automático climatic',
        'Control crucero',
        'Sensores estacionamiento traseros',
        'Tapizado en cuero sintético',
        'Espejos eléctricos con desempañador',
        'Alzacristales eléctricos one-touch',
      ],
      exterior: [
        'Llantas de aleación Korama 16" (245/70 R16)',
        'Faros VW LED + DRL',
        'Faros traseros halogenos con antiniebla',
        'Paragolpes delantero color carrocería',
        'Paragolpes trasero negro mate',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        '4 parlantes + 2 tweeters',
        '3 puertos USB (1 A frontal + 2 C traseros)',
        'Cuadro instrumentos analógico con monocromo 3,5"',
      ],
    },
    'comfort-mt': {
      motor: {
        nombre: '2.0 BiTDI',
        subtitulo: '1.968 cc · 4 cilindros bi-turbodiesel · common-rail',
        potencia: '180 CV',
        torque: '400 Nm',
        torqueRpm: '@ 1.500-2.250 rpm',
        caja: 'Manual 6 velocidades',
        traccion: '4x2 (tracción trasera)',
      },
      destacados: [
        'Cámara visión trasera',
        'Faros antiniebla LED con luz de giro',
        'Llantas Tronador 17"',
        'Volante y selectora en cuero',
        'Navegacion de mapas',
      ],
      seguridad: [
        '2 airbags frontales + 2 laterales + 2 cortina',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Bloqueo mecánico de diferencial + EDS',
        'Espejo interior anti-encandilamiento automático',
        'Alarma antirrobo con sensor volumétrico',
      ],
      confort: [
        'Climatizador semi-automático climatic',
        'Control crucero',
        'Sensores estacionamiento traseros',
        'Cámara visión trasera',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Coming & Leaving Home',
        'Volante y selectora revestidos en cuero',
        'Tapizado en tela',
      ],
      exterior: [
        'Llantas de aleación Tronador 17" (245/65 R17)',
        'Cobertor de pasaruedas (overfenders)',
        'Faros antiniebla delanteros LED con luz estática de giro',
        'Carcasa de espejos color carrocería',
        'Manijas color carrocería',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
    'comfort-at': {
      motor: {
        nombre: '2.0 BiTDI',
        subtitulo: '1.968 cc · 4 cilindros bi-turbodiesel · common-rail',
        potencia: '180 CV',
        torque: '420 Nm',
        torqueRpm: '@ 1.750-2.250 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x2 (tracción trasera)',
      },
      destacados: [
        'Caja automática 8 velocidades',
        'Cámara visión trasera',
        'Faros antiniebla LED con luz de giro',
        'Llantas Tronador 17"',
        'Volante y selectora en cuero',
      ],
      seguridad: [
        '2 airbags frontales + 2 laterales + 2 cortina',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Bloqueo mecánico de diferencial + EDS',
        'Espejo interior anti-encandilamiento automático',
        'Alarma antirrobo con sensor volumétrico',
      ],
      confort: [
        'Climatizador semi-automático climatic',
        'Control crucero',
        'Sensores estacionamiento traseros',
        'Cámara visión trasera',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
        'Coming & Leaving Home',
        'Volante y selectora revestidos en cuero',
        'Tapizado en tela',
      ],
      exterior: [
        'Llantas de aleación Tronador 17" (245/65 R17)',
        'Cobertor de pasaruedas (overfenders)',
        'Faros antiniebla delanteros LED con luz estática de giro',
        'Carcasa de espejos color carrocería',
        'Manijas color carrocería',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
    'comfort-v6': {
      motor: {
        nombre: 'V6 3.0 TDI',
        subtitulo: '2.967 cc · 6 cilindros en V turbodiesel · common-rail',
        potencia: '258 CV',
        torque: '580 Nm',
        torqueRpm: '@ 1.400-3.000 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x4 integral permanente con Torsen',
      },
      destacados: [
        'Motor V6 258 CV',
        '4x4 permanente con diferencial Torsen',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Cámara visión trasera + sensores',
        'Llantas Tronador 17"',
      ],
      seguridad: [
        '6 airbags totales',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Bloqueo mecánico de diferencial + EDS',
        'Frenado post-colisión',
        'Alarma antirrobo con sensor volumétrico',
      ],
      confort: [
        'Climatizador semi-automático climatic',
        'Control crucero',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Regulación lumbar',
        'Cámara visión trasera',
        'Sensores estacionamiento delanteros y traseros',
        'Coming & Leaving Home',
        'Limpiaparabrisas automático con sensor de lluvia',
        'Sensor crepuscular',
      ],
      exterior: [
        'Llantas de aleación Tronador 17" (245/65 R17)',
        'Cobertor de pasaruedas (overfenders)',
        'Faros VW LED + DRL + antiniebla LED',
        'Carcasa de espejos color carrocería',
        'Paragolpes delantero color carrocería',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
    'highline-v6': {
      motor: {
        nombre: 'V6 3.0 TDI',
        subtitulo: '2.967 cc · 6 cilindros en V turbodiesel · common-rail',
        potencia: '258 CV',
        torque: '580 Nm',
        torqueRpm: '@ 1.400-3.000 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x4 integral permanente con Torsen',
      },
      destacados: [
        'Safer Tag (alertas inteligentes)',
        'TPMS (presión de neumáticos)',
        'Climatronic bi-zona',
        'Calefaccion de asientos',
        'Llantas Zapaleri 18" diamantadas',
      ],
      seguridad: [
        '6 airbags totales',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Safer Tag (alerta carril, colisión, peatones, limite velocidad)',
        'TPMS (control presión neumáticos)',
        'Frenado post-colisión',
      ],
      confort: [
        'Climatizador automático climatronic bi-zona',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Calefaccion de asientos',
        'Regulación lumbar',
        'Abatimiento eléctrico de espejos exteriores',
        'Cámara visión trasera + sensores delanteros y traseros',
        'Coming & Leaving Home',
        'Tapizado cuero perforado',
        'Revestimiento interior oscurecido',
      ],
      exterior: [
        'Llantas diamantadas Zapaleri 18" (255/60 R18)',
        'Grilla frontal iluminada',
        'Paragolpes trasero cromado',
        'Barra de estilo de acero inoxidable (styling bar)',
        'Estribos ovales de acero inoxidable',
        'Cobertor/tapa de motor',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
        'Insonorizante de capot',
      ],
    },
    'extreme-v6': {
      motor: {
        nombre: 'V6 3.0 TDI',
        subtitulo: '2.967 cc · 6 cilindros en V turbodiesel · common-rail',
        potencia: '258 CV',
        torque: '580 Nm',
        torqueRpm: '@ 1.400-3.000 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x4 integral permanente con Torsen',
      },
      destacados: [
        'Llantas Aconcagua 20" diamantadas',
        'Sportbar deportivo',
        'Estribos planos de aluminio',
        'Paragolpes trasero cromado',
        'Safer Tag + TPMS',
      ],
      seguridad: [
        '6 airbags totales',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Safer Tag (alerta carril, colisión, peatones, limite velocidad)',
        'TPMS (control presión neumáticos)',
        'Frenado post-colisión',
      ],
      confort: [
        'Climatizador automático climatronic bi-zona',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Calefaccion de asientos',
        'Regulación lumbar',
        'Abatimiento eléctrico de espejos exteriores',
        'Cámara visión trasera + sensores delanteros y traseros',
        'Coming & Leaving Home',
        'Tapizado cuero perforado',
        'Revestimiento interior oscurecido',
      ],
      exterior: [
        'Llantas diamantadas Aconcagua 20" (255/50 R20)',
        'Rueda auxilio diamantada 20"',
        'Barra deportiva sportbar',
        'Estribos laterales planos de aluminio',
        'Paragolpes trasero cromado',
        'Grilla frontal iluminada',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
    blackstyle: {
      motor: {
        nombre: 'V6 3.0 TDI',
        subtitulo: '2.967 cc · 6 cilindros en V turbodiesel · common-rail',
        potencia: '258 CV',
        torque: '580 Nm',
        torqueRpm: '@ 1.400-3.000 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x4 integral permanente con Torsen',
      },
      destacados: [
        'Llantas Aconcagua 20" diamantadas oscurecidas',
        'Carcasa de espejos negro profundo',
        'Logotipos AMAROK oscurecidos',
        'Paragolpes trasero negro mate',
        'Mayor despeje (245 mm)',
      ],
      seguridad: [
        '6 airbags totales',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Safer Tag (alerta carril, colisión, peatones, limite velocidad)',
        'TPMS (control presión neumáticos)',
        'Frenado post-colisión',
      ],
      confort: [
        'Climatizador automático climatronic bi-zona',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Calefaccion de asientos',
        'Regulación lumbar',
        'Abatimiento eléctrico de espejos exteriores',
        'Cámara visión trasera + sensores delanteros y traseros',
        'Coming & Leaving Home',
        'Tapizado cuero perforado',
        'Revestimiento interior oscurecido',
      ],
      exterior: [
        'Llantas diamantadas oscurecidas Aconcagua 20"',
        'Rueda auxilio diamantada oscurecida 20"',
        'Paragolpes trasero negro mate',
        'Carcasa de espejos negro profundo con detalles cromo',
        'Manijas negro profundo',
        'Estribos laterales ovales negro mate',
        'Logotipos AMAROK oscurecidos',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
    hero: {
      motor: {
        nombre: 'V6 3.0 TDI',
        subtitulo: '2.967 cc · 6 cilindros en V turbodiesel · common-rail',
        potencia: '258 CV',
        torque: '580 Nm',
        torqueRpm: '@ 1.400-3.000 rpm',
        caja: 'Automática 8 vel con convertidor de par',
        traccion: '4x4 integral permanente con Torsen',
      },
      destacados: [
        'Mayor despeje 245 mm',
        'Ángulos off-road 27,2° / 20,5° / 23,8°',
        'Llantas Aconcagua 20" diamantadas',
        'Embellecedores de tuercas',
        'Vadeo 500 mm',
      ],
      seguridad: [
        '6 airbags totales',
        'ABS off-road + BAS',
        'ESP + ASR + MSR',
        'TSA + HSA + HDC',
        'Safer Tag (alerta carril, colisión, peatones, limite velocidad)',
        'TPMS (control presión neumáticos)',
        'Frenado post-colisión',
      ],
      confort: [
        'Climatizador automático climatronic bi-zona',
        'Asientos eléctricos ergoComfort 14 posiciones',
        'Calefaccion de asientos',
        'Regulación lumbar',
        'Abatimiento eléctrico de espejos exteriores',
        'Cámara visión trasera + sensores delanteros y traseros',
        'Coming & Leaving Home',
        'Tapizado cuero perforado',
        'Revestimiento interior oscurecido',
      ],
      exterior: [
        'Llantas diamantadas Aconcagua 20" (255/50 R20)',
        'Embellecedores de tuercas',
        'Barra deportiva sportbar',
        'Estribos laterales planos de aluminio',
        'Paragolpes trasero cromado',
        'Grilla frontal iluminada',
      ],
      tecnologia: [
        'Composition Touch 9" con App-Connect',
        'Navegacion de mapas',
        '4 parlantes + 2 tweeters',
        '3 puertos USB',
      ],
    },
  },

  taos: {
    comfortline: {
      motor: {
        nombre: '1.4 TSI',
        subtitulo: '1.395 cc · 4 cilindros turbo · nafta · Euro 6',
        potencia: '150 CV',
        torque: '250 Nm',
        torqueRpm: '@ 1.400 rpm',
        caja: 'Tiptronic 8 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Faros IQ Light con luz de curva dinamica',
        'ACC adaptativo stop & go',
        'Climatronic 2 zonas táctil',
        'KESSY (acceso sin llave)',
        'VW Play Connect 10" semiflotante',
      ],
      seguridad: [
        'Airbags conductor + acompañante (con desactivación)',
        '2 airbags cortina + 2 laterales',
        'ACC adaptativo stop & go con limitador',
        'AEB con detección de peatones',
        'Frenado emergencia post-colisión',
        'Detector de fatiga',
        'Apoyacabezas activos',
      ],
      confort: [
        'Climatizador automático Climatronic 2 zonas táctil',
        'Difusores aire traseros',
        'KESSY (acceso sin llave)',
        'Freno de estacionamiento eléctrico',
        'Asiento conductor con lumbar eléctrico',
        'Cargador inductivo',
        'Cámara visión trasera',
        'Sensor estacionamiento delantero y trasero',
        'Volante en cuero con levas',
      ],
      exterior: [
        'Llantas de aleación 18" Fiji (215/55 R18)',
        'Faros IQ Light con luz de curva dinamica',
        'Logo VW trasero iluminado',
        'Luces traseras LED + Light Strip',
      ],
      tecnologia: [
        'VW Play Connect 10" semiflotante',
        'Active Info Display 100% digital',
        'Mi VW Connect',
        '6 altavoces',
        'App-Connect con y sin cable',
      ],
    },
    highline: {
      motor: {
        nombre: '1.4 TSI',
        subtitulo: '1.395 cc · 4 cilindros turbo · nafta · Euro 6',
        potencia: '150 CV',
        torque: '250 Nm',
        torqueRpm: '@ 1.400 rpm',
        caja: 'Tiptronic 8 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Travel Assist + Lane Assist',
        'Techo solar panorámico',
        'Llantas 19" Plus',
        '6 altavoces + subwoofer',
        'Grilla frontal LED iluminada',
      ],
      seguridad: [
        'Airbags conductor + acompañante (con desactivación)',
        '2 airbags cortina + 2 laterales',
        'Travel Assist + Lane Assist',
        'Emergency Assist',
        'Detector punto ciego con tráfico cruzado trasero',
        'AEB con detección de peatones',
        'ACC adaptativo stop & go',
        'Light Assist',
      ],
      confort: [
        'Climatizador automático Climatronic 2 zonas táctil',
        'Difusores aire traseros',
        'KESSY (acceso sin llave)',
        'Freno de estacionamiento eléctrico',
        'Asiento conductor con lumbar eléctrico',
        'Cargador inductivo',
        'Cámara visión trasera',
        'Sensor estacionamiento delantero y trasero',
        'Tapizado parcial en cuero',
        'Selector de perfil de conducción',
      ],
      exterior: [
        'Llantas de aleación 19" Plus (235/45 R19)',
        'Faros IQ Light con AFS (ajuste dinamico)',
        'Grilla frontal LED iluminada',
        'Techo solar panorámico',
        'Barras de techo en plata anodizada',
        'Moldura inferior de ventanas en cromo',
      ],
      tecnologia: [
        'VW Play Connect 10" semiflotante',
        'Active Info Display 100% digital',
        'Mi VW Connect',
        '6 altavoces + 1 subwoofer',
        'App-Connect con y sin cable',
        'Pedales deportivos en aluminio',
      ],
    },
    'highline-bitono': {
      motor: {
        nombre: '1.4 TSI',
        subtitulo: '1.395 cc · 4 cilindros turbo · nafta · Euro 6',
        potencia: '150 CV',
        torque: '250 Nm',
        torqueRpm: '@ 1.400 rpm',
        caja: 'Tiptronic 8 vel (automática)',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Techo Bi-Tono color negro',
        'Espejos color negro brillante',
        'Travel Assist + Lane Assist',
        'Techo solar panorámico',
        'Llantas 19" Plus',
      ],
      seguridad: [
        'Airbags conductor + acompañante (con desactivación)',
        '2 airbags cortina + 2 laterales',
        'Travel Assist + Lane Assist',
        'Emergency Assist',
        'Detector punto ciego con tráfico cruzado trasero',
        'AEB con detección de peatones',
        'ACC adaptativo stop & go',
        'Light Assist',
      ],
      confort: [
        'Climatizador automático Climatronic 2 zonas táctil',
        'Difusores aire traseros',
        'KESSY (acceso sin llave)',
        'Freno de estacionamiento eléctrico',
        'Asiento conductor con lumbar eléctrico',
        'Cargador inductivo',
        'Cámara visión trasera',
        'Sensor estacionamiento delantero y trasero',
        'Tapizado parcial en cuero',
        'Selector de perfil de conducción',
      ],
      exterior: [
        'Llantas de aleación 19" Plus (235/45 R19)',
        'Techo Bi-Tono color negro',
        'Espejos exteriores color negro brillante',
        'Faros IQ Light con AFS (ajuste dinamico)',
        'Grilla frontal LED iluminada',
        'Techo solar panorámico',
      ],
      tecnologia: [
        'VW Play Connect 10" semiflotante',
        'Active Info Display 100% digital',
        'Mi VW Connect',
        '6 altavoces + 1 subwoofer',
        'App-Connect con y sin cable',
        'Pedales deportivos en aluminio',
      ],
    },
  },

  tiguan: {
    rline: {
      motor: {
        nombre: '1.4 TSI',
        subtitulo: '1.395 cc · 4 cilindros turbo · nafta · Euro 6 Plus',
        potencia: '150 CV',
        torque: '250 Nm',
        torqueRpm: '@ 1.500-3.500 rpm',
        caja: 'DSG 7 velocidades',
        traccion: 'Tracción delantera',
      },
      destacados: [
        'Asientos con calefacción, ventilación y masajes',
        'Travel Assist con stop & go',
        'Cámara visión 360°',
        'Faros LED Matrix',
        'Multimedia 15" flotante',
      ],
      seguridad: [
        'Airbags conductor + acompañante (con desactivación)',
        '2 airbags cortina + 2 laterales',
        'Travel Assist con stop & go',
        'ACC adaptativo stop & go con limitador',
        'AEB con detección de peatones y ciclistas',
        'Detector punto ciego con tráfico cruzado trasero',
        'Lane Assist + Light Assist',
        'Park Assist (estacionamiento autónomo inteligente)',
      ],
      confort: [
        'Climatizador automático 3 zonas integrado en multimedia',
        'Asiento conductor y pasajero eléctrico 12 vías con memoria',
        'Asientos con calefacción, ventilación y masajes',
        'KESSY (acceso sin llave)',
        'Techo panorámico',
        'Easy Open (apertura portón con pedal virtual)',
        'Volante en cuero con levas y calefaccionado',
        'Tapizado parcial cuero',
        'Sensor estacionamiento delantero y trasero',
      ],
      exterior: [
        'Llantas de aleación 19" Grinder (255/45 R19)',
        'Faros LED Matrix',
        'Grilla frontal LED iluminada',
        'Logo VW delantero y trasero iluminado',
        'Manijas exteriores color carrocería con iluminación',
        'Paragolpes deportivos R-Line color carrocería',
      ],
      tecnologia: [
        'Multimedia 15" flotante',
        'VW Digital Cockpit 100% digital',
        'Head Up Display',
        'Cámara visión 360°',
        'Cargador inductivo',
        'Iluminación ambiental con animación',
      ],
    },
  },
};
